'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useLocale,useTranslations} from 'next-intl';
import {usePathname,useRouter} from 'next/navigation';
import {Moon,Sun,Languages,Menu,X} from 'lucide-react';
import {useTheme} from 'next-themes';
import {useState} from 'react';
export function Header(){const t=useTranslations('nav');const locale=useLocale();const path=usePathname();const router=useRouter();const {theme,setTheme}=useTheme();const [open,setOpen]=useState(false);const switchLocale=()=>router.push(path.replace(`/${locale}`,locale==='en'?'/hi':'/en'));const links=[['home',''],['products','products'],['services','services'],['industries','industries'],['portfolio','portfolio'],['pricing','pricing']];return <header className="sticky top-0 z-50 border-b border-[var(--line)] bg-[color:var(--surface)] backdrop-blur-xl"><div className="container flex min-h-[82px] items-center justify-between gap-5"><Link href={`/${locale}`} className="flex items-center gap-3"><Image src="/logo/systemmaster.png" alt="SystemMaster Automations" width={66} height={66} className="h-14 w-14 object-contain" priority/><div><div className="display text-[1.05rem] font-extrabold">SystemMaster</div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--gold)]">Automations</div></div></Link><nav className="hidden items-center gap-1 lg:flex">{links.map(([k,r])=><Link key={k} href={`/${locale}/${r}`} className="rounded-full px-3 py-2 text-sm font-bold text-[var(--muted)] hover:bg-[var(--surface-strong)] hover:text-[var(--text)]">{t(k)}</Link>)}</nav><div className="hidden items-center gap-2 lg:flex"><button onClick={switchLocale} className="btn btn-ghost !min-h-10 !px-3" aria-label="Change language"><Languages size={17}/>{locale.toUpperCase()}</button><button onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="btn btn-ghost !min-h-10 !px-3" aria-label="Toggle theme">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><Link href={`/${locale}/contact`} className="btn btn-primary !min-h-11">{t('demo')}</Link></div><button className="lg:hidden" onClick={()=>setOpen(!open)} aria-label="Open menu">{open?<X/>:<Menu/>}</button></div>{open&&<div className="container pb-5 lg:hidden">{links.map(([k,r])=><Link onClick={()=>setOpen(false)} key={k} href={`/${locale}/${r}`} className="block border-b border-[var(--line)] py-3 font-bold">{t(k)}</Link>)}<div className="mt-4 flex gap-2"><button onClick={switchLocale} className="btn btn-ghost"><Languages size={17}/>{locale.toUpperCase()}</button><Link href={`/${locale}/contact`} className="btn btn-primary flex-1">{t('demo')}</Link></div></div>}</header>}
