'use client';
import Link from 'next/link';
import {motion} from 'framer-motion';
import {ArrowRight,CheckCircle2,Factory,Layers3,Sparkles,Target} from 'lucide-react';
import type {IndustryDetail} from '@/data/industries';
import type {Locale} from '@/data/catalog';
import {Reveal} from '@/components/reveal';

export function IndustryDetailPage({industry,locale}:{industry:IndustryDetail;locale:Locale}){
 const hi=locale==='hi';
 const t={eyebrow:hi?'इंडस्ट्री सॉल्यूशन':'Industry Solution',problems:hi?'मुख्य चुनौतियाँ':'Common Challenges',solutions:hi?'हम क्या समाधान देते हैं':'How We Solve It',modules:hi?'सुझाए गए मॉड्यूल':'Recommended Modules',outcomes:hi?'आपको क्या लाभ मिलेगा':'Business Outcomes',cta:hi?'अपनी इंडस्ट्री के लिए डेमो बुक करें':'Book an Industry Demo',custom:hi?'आपका workflow अलग है? हम उसी के अनुसार सिस्टम customize कर सकते हैं।':'Your workflow is different? We can tailor the system around your exact process.'};
 return <main>
  <section className="relative overflow-hidden py-20 md:py-28"><div className="container grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="eyebrow"><Sparkles size={15}/>{t.eyebrow}</motion.div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.06}} className="display mt-5 text-5xl font-black md:text-7xl">{industry.name[locale]}</motion.h1><motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.12}} className="mt-6 max-w-3xl text-xl font-bold leading-8">{industry.tagline[locale]}</motion.p><motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.18}} className="muted mt-4 max-w-3xl text-lg leading-8">{industry.description[locale]}</motion.p><Link href={`/${locale}/contact`} className="btn btn-gold mt-8">{t.cta}<ArrowRight size={18}/></Link></div><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="card flex min-h-[360px] items-center justify-center bg-gradient-to-br from-blue-500/20 to-amber-400/10"><Factory size={120} className="text-[var(--gold)] opacity-90"/></motion.div></div></section>
  <section className="section pt-4"><div className="container grid gap-8 lg:grid-cols-2"><Reveal><div className="card h-full p-8"><Target className="text-[var(--gold)]"/><h2 className="display mt-4 text-3xl font-black">{t.problems}</h2><div className="mt-6 grid gap-4">{industry.problems.map(x=><div key={x.en} className="rounded-2xl border border-[var(--line)] p-4 font-bold">{x[locale]}</div>)}</div></div></Reveal><Reveal delay={.08}><div className="card h-full p-8"><CheckCircle2 className="text-emerald-500"/><h2 className="display mt-4 text-3xl font-black">{t.solutions}</h2><div className="mt-6 grid gap-4">{industry.solutions.map(x=><div key={x.en} className="rounded-2xl border border-[var(--line)] p-4 font-bold">{x[locale]}</div>)}</div></div></Reveal></div></section>
  <section className="section"><div className="container"><Reveal><div className="text-center"><Layers3 className="mx-auto text-[var(--primary)]"/><h2 className="display mt-4 text-4xl font-black">{t.modules}</h2></div></Reveal><div className="grid-3 mt-9">{industry.modules.map((x,i)=><Reveal key={x.en} delay={i*.04}><div className="card p-6 font-extrabold">{x[locale]}</div></Reveal>)}</div></div></section>
  <section className="section pt-4"><div className="container"><Reveal><div className="card p-8 md:p-12"><h2 className="display text-4xl font-black">{t.outcomes}</h2><div className="grid-4 mt-8">{industry.outcomes.map(x=><div key={x.en} className="rounded-2xl border border-[var(--line)] p-5 font-bold">{x[locale]}</div>)}</div><p className="muted mt-8 text-lg">{t.custom}</p><Link href={`/${locale}/contact`} className="btn btn-primary mt-6">{t.cta}<ArrowRight size={18}/></Link></div></Reveal></div></section>
 </main>
}
