'use client';

import Image from 'next/image';
import Link from 'next/link';
import {useLocale} from 'next-intl';
import {motion} from 'framer-motion';
import {
  ArrowRight, BadgeCheck, BarChart3, Bot, Boxes, Building2, Check, Cloud,
  Code2, Factory, Globe2, HeartPulse, Laptop, MapPinned, MessageCircle,
  PackageCheck, Plane, Printer, Rocket, ShieldCheck, Smartphone, Sparkles,
  Users, Warehouse, Workflow, Wrench
} from 'lucide-react';
import {products, services, industries} from '@/data/site';
import {Reveal} from '@/components/reveal';

const copy = {
  en: {
    products: {eyebrow:'Ready-to-use cloud software', title:'Start today with proven SystemMaster products', desc:'Choose a live SaaS product for immediate use, or speak with us for a tailored implementation.', custom:'Need a customized version?', customDesc:'We can extend modules, workflows, reports, integrations and permissions around your business.'},
    services: {eyebrow:'Custom development', title:'Software built around the way your business works', desc:'From discovery to deployment, we design secure, scalable business systems with clear ownership and long-term support.'},
    industries: {eyebrow:'Industry solutions', title:'Built for real operational workflows', desc:'We combine ready products and custom development for industry-specific processes, reporting and automation.'},
    portfolio: {eyebrow:'Portfolio & live demos', title:'See the systems we can build', desc:'Explore working ERP, workflow, inventory, analytics and performance demonstrations.'},
    pricing: {eyebrow:'Simple product pricing', title:'Start small. Scale as your team grows.', desc:'Ready-to-use products have transparent pricing. Custom software is scoped after understanding your workflow.'},
    contact: {eyebrow:'Free consultation', title:'Tell us what you want to automate', desc:'Share your business process and challenges. We will suggest the most practical product or custom solution.'},
    common:{visit:'Visit Product',demo:'Book Demo',talk:'Talk to an Expert',learn:'Explore',ready:'Ready to Use',offer:'Offer Price'}
  },
  hi: {
    products: {eyebrow:'तैयार क्लाउड सॉफ्टवेयर', title:'SystemMaster के तैयार प्रोडक्ट से आज ही शुरुआत करें', desc:'तुरंत उपयोग के लिए लाइव SaaS प्रोडक्ट चुनें या अपने व्यवसाय के अनुसार कस्टम समाधान बनवाएं।', custom:'कस्टम वर्जन चाहिए?', customDesc:'हम आपके व्यवसाय के अनुसार मॉड्यूल, वर्कफ़्लो, रिपोर्ट, इंटीग्रेशन और परमिशन विकसित कर सकते हैं।'},
    services: {eyebrow:'कस्टम डेवलपमेंट', title:'आपके बिजनेस प्रोसेस के अनुसार बनाया गया सॉफ्टवेयर', desc:'डिस्कवरी से डिप्लॉयमेंट तक हम सुरक्षित, स्केलेबल बिजनेस सिस्टम और लंबे समय का सपोर्ट देते हैं।'},
    industries: {eyebrow:'इंडस्ट्री समाधान', title:'वास्तविक ऑपरेशनल वर्कफ़्लो के लिए बनाया गया', desc:'हम इंडस्ट्री के अनुसार प्रोसेस, रिपोर्टिंग और ऑटोमेशन के लिए तैयार प्रोडक्ट और कस्टम डेवलपमेंट को जोड़ते हैं।'},
    portfolio: {eyebrow:'पोर्टफोलियो और लाइव डेमो', title:'देखिए हम किस प्रकार के सिस्टम बना सकते हैं', desc:'ERP, workflow, inventory, analytics और performance के working demos देखें।'},
    pricing: {eyebrow:'सरल प्रोडक्ट प्राइसिंग', title:'छोटी शुरुआत करें और टीम के साथ स्केल करें', desc:'तैयार प्रोडक्ट की स्पष्ट कीमत है। कस्टम सॉफ्टवेयर की कीमत workflow समझने के बाद तय होती है।'},
    contact: {eyebrow:'फ्री कंसल्टेशन', title:'बताइए आप क्या ऑटोमेट करना चाहते हैं', desc:'अपना business process और challenges साझा करें। हम practical product या custom solution suggest करेंगे।'},
    common:{visit:'प्रोडक्ट खोलें',demo:'डेमो बुक करें',talk:'एक्सपर्ट से बात करें',learn:'और जानें',ready:'तुरंत उपलब्ध',offer:'ऑफर प्राइस'}
  }
} as const;

function Hero({eyebrow,title,desc}:{eyebrow:string;title:string;desc:string}){
  return <section className="relative overflow-hidden py-20 md:py-28"><div className="container text-center"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="eyebrow"><Sparkles size={15}/>{eyebrow}</motion.div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="display mx-auto mt-5 max-w-5xl text-5xl font-black md:text-7xl">{title}</motion.h1><motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.16}} className="muted mx-auto mt-6 max-w-3xl text-lg leading-8">{desc}</motion.p></div></section>
}

export function ProductsPage(){
  const locale=useLocale() as 'en'|'hi'; const t=copy[locale]||copy.en;
  return <main><Hero {...t.products}/><section className="section pt-4"><div className="container"><div className="grid-3">{products.map((x,i)=><Reveal key={x.key} delay={i*.08}><article className="card flex h-full flex-col p-7"><div className="flex items-start justify-between gap-4"><Image src={x.logo} alt={x.name} width={130} height={90} className="h-24 w-32 object-contain"/><span className="rounded-full bg-emerald-500/15 px-3 py-1 text-xs font-extrabold text-emerald-500">{t.common.ready}</span></div><h2 className="display mt-6 text-3xl font-black"><Link href={`/${locale}/products/${x.key}`} className="transition hover:text-[var(--primary)]">{x.name}</Link></h2><div className="mt-3 text-xl font-black text-[var(--gold)]">{x.price}</div><ul className="muted mt-6 grid gap-3">{x.features.map(f=><li key={f} className="flex gap-3"><Check size={18} className="mt-1 shrink-0 text-emerald-500"/>{f}</li>)}</ul><div className="mt-auto flex flex-wrap gap-3 pt-8"><Link href={`/${locale}/products/${x.key}`} className="btn btn-primary flex-1">{t.common.learn}<ArrowRight size={17}/></Link><a href={x.href} target="_blank" rel="noreferrer" className="btn btn-ghost">{t.common.visit}</a></div></article></Reveal>)}</div><Reveal><div className="card mt-12 grid gap-8 p-8 md:grid-cols-[1fr_auto] md:items-center md:p-12"><div><div className="eyebrow"><Wrench size={15}/>{t.products.custom}</div><h2 className="display mt-4 text-3xl font-black md:text-5xl">{t.products.custom}</h2><p className="muted mt-4 max-w-3xl text-lg">{t.products.customDesc}</p></div><Link href={`/${locale}/contact`} className="btn btn-gold">{t.common.talk}<ArrowRight size={18}/></Link></div></Reveal></div></section></main>
}

const serviceIcons=[Globe2,Laptop,Smartphone,Boxes,Users,Workflow,BarChart3,Code2,MessageCircle,Cloud,Bot,Rocket];
export function ServicesPage(){const locale=useLocale() as 'en'|'hi'; const t=copy[locale]||copy.en;const slugs=['website-development','web-app-development','mobile-app-development','erp-development','crm-development','hrms-development','ai-automation','whatsapp-automation','dashboard-bi','api-integration','cloud-applications','custom-enterprise'];return <main><Hero {...t.services}/><section className="section pt-4"><div className="container"><div className="grid-3">{services.map((s,i)=>{const Icon=serviceIcons[i%serviceIcons.length];return <Reveal key={s} delay={i*.04}><article className="card h-full p-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-500/15 text-[var(--primary)]"><Icon/></div><h2 className="display mt-6 text-2xl font-black"><Link href={`/${locale}/services/${slugs[i]}`} className="transition hover:text-[var(--primary)]">{s}</Link></h2><p className="muted mt-4">Strategy, UI/UX, development, integrations, testing, deployment and ongoing support.</p><Link href={`/${locale}/services/${slugs[i]}`} className="mt-6 inline-flex items-center gap-2 font-extrabold text-[var(--primary)]">{t.common.learn}<ArrowRight size={16}/></Link></article></Reveal>})}</div></div></section></main>}

const industryIcons=[Factory,PackageCheck,Printer,Warehouse,HeartPulse,Building2,Plane,MapPinned,Users,Boxes,Workflow,BarChart3];
export function IndustriesPage(){const locale=useLocale() as 'en'|'hi'; const t=copy[locale]||copy.en;return <main><Hero {...t.industries}/><section className="section pt-4"><div className="container"><div className="grid-4">{industries.map((s,i)=>{const Icon=industryIcons[i%industryIcons.length];return <Reveal key={s} delay={i*.035}><article className="card h-full p-6"><Icon className="text-[var(--gold)]"/><h2 className="display mt-5 text-xl font-black">{s}</h2><p className="muted mt-3 text-sm">ERP, CRM, reporting, mobile workflows and automation designed around industry operations.</p><Link href={`/${locale}/contact`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-[var(--primary)]">{t.common.learn}<ArrowRight size={15}/></Link></article></Reveal>})}</div></div></section></main>}

const demos=[
 ['Full ERP Demo','/demos/demo-erp-full.html','ERP'],['ERP Dashboard','/demos/demo-erp.html','ERP'],['FMS Workflow','/demos/demo-fms.html','Workflow'],['Inventory Management','/demos/demo-ims.html','Inventory'],['Production Management','/demos/demo-pms.html','Manufacturing'],['Business Analytics','/demos/demo-analytics.html','Analytics'],['Performance Dashboard','/demos/demo-performance.html','HR & Performance'],['Certificate System','/demos/demo-certificates.html','Automation']
];
export function PortfolioPage(){const locale=useLocale() as 'en'|'hi'; const t=copy[locale]||copy.en;return <main><Hero {...t.portfolio}/><section className="section pt-4"><div className="container"><div className="grid-3">{demos.map((d,i)=><Reveal key={d[0]} delay={i*.05}><article className="card flex h-full flex-col overflow-hidden"><div className="flex min-h-48 items-center justify-center bg-gradient-to-br from-blue-500/20 to-amber-400/10"><BarChart3 size={64} className="text-[var(--primary)]"/></div><div className="flex flex-1 flex-col p-6"><span className="eyebrow">{d[2]}</span><h2 className="display mt-3 text-2xl font-black">{d[0]}</h2><p className="muted mt-3">Interactive demonstration of a real business workflow and reporting experience.</p><a href={d[1]} target="_blank" className="btn btn-primary mt-6">Live Demo<ArrowRight size={17}/></a></div></article></Reveal>)}</div></div></section></main>}

export function PricingPage(){const locale=useLocale() as 'en'|'hi'; const t=copy[locale]||copy.en;return <main><Hero {...t.pricing}/><section className="section pt-4"><div className="container"><div className="grid-3">{products.map((x,i)=><Reveal key={x.key} delay={i*.08}><article className="card flex h-full flex-col p-7"><BadgeCheck className="text-emerald-500"/><h2 className="display mt-5 text-2xl font-black">{x.name}</h2><div className="mt-4 text-3xl font-black text-[var(--gold)]">{x.price}</div><p className="muted mt-4">Cloud hosted, ready to use and supported by SystemMaster.</p><ul className="muted mt-6 grid gap-3">{x.features.map(f=><li key={f} className="flex gap-2"><Check size={17} className="text-emerald-500"/>{f}</li>)}</ul><a href={x.href} target="_blank" className="btn btn-primary mt-auto pt-0">{t.common.visit}<ArrowRight size={16}/></a></article></Reveal>)}</div><Reveal><div className="card mt-12 p-8 text-center md:p-12"><ShieldCheck className="mx-auto text-[var(--gold)]" size={42}/><h2 className="display mt-5 text-4xl font-black">Custom software is quote-based</h2><p className="muted mx-auto mt-4 max-w-2xl">We first understand users, modules, workflow, reports, integrations and deployment needs. Then we share a clear scope and commercial proposal.</p><Link href={`/${locale}/contact`} className="btn btn-gold mt-7">{t.common.talk}<ArrowRight size={17}/></Link></div></Reveal></div></section></main>}

export function ContactPage(){const locale=useLocale() as 'en'|'hi'; const t=copy[locale]||copy.en;return <main><Hero {...t.contact}/><section className="section pt-4"><div className="container grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><Reveal><aside className="card p-7 md:p-9"><h2 className="display text-3xl font-black">SystemMaster Automations</h2><div className="muted mt-6 grid gap-4"><p><strong className="text-[var(--text)]">Founder:</strong><br/>Sunil Tiwari</p><p><strong className="text-[var(--text)]">Email:</strong><br/><a href="mailto:Connect@systemmaster.in">Connect@systemmaster.in</a></p><p><strong className="text-[var(--text)]">Phone:</strong><br/><a href="tel:+919027965956">+91 90279 65956</a></p><p><strong className="text-[var(--text)]">Website:</strong><br/>www.systemmaster.in</p></div><a href="https://wa.me/919027965956" target="_blank" className="btn btn-gold mt-7 w-full"><MessageCircle size={18}/>WhatsApp</a></aside></Reveal><Reveal delay={.08}><form className="card grid gap-5 p-7 md:grid-cols-2 md:p-9" action="mailto:Connect@systemmaster.in" method="post" encType="text/plain"><label className="grid gap-2 font-bold">Name<input required name="name" className="form-field" placeholder="Your name"/></label><label className="grid gap-2 font-bold">Company<input name="company" className="form-field" placeholder="Company name"/></label><label className="grid gap-2 font-bold">Phone<input required name="phone" className="form-field" placeholder="Mobile number"/></label><label className="grid gap-2 font-bold">Email<input type="email" name="email" className="form-field" placeholder="Email address"/></label><label className="grid gap-2 font-bold md:col-span-2">Requirement<select name="interest" className="form-field"><option>Ready-to-use product</option><option>Custom ERP / CRM / HRMS</option><option>Website or mobile app</option><option>AI / WhatsApp automation</option><option>Other requirement</option></select></label><label className="grid gap-2 font-bold md:col-span-2">Message<textarea required name="message" className="form-field min-h-36 resize-y" placeholder="Describe your workflow and requirement"/></label><button className="btn btn-primary md:col-span-2" type="submit">Send Requirement<ArrowRight size={18}/></button></form></Reveal></div></section></main>}
